graylog-mongo:
    image: "mongo:3"
graylog-elasticsearch:
    image: "elasticsearch:2"
    command: "elasticsearch -Des.cluster.name='graylog'"
graylog:
    image: graylog/graylog:2.3.0-1
    environment:
        GRAYLOG_PASSWORD_SECRET: somepasswordpepper
        GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
        GRAYLOG_WEB_ENDPOINT_URI: "http://127.0.0.1:${PORT}/api"
    links:
    - graylog-mongo:mongo
    - graylog-elasticsearch:graylog-elasticsearch
    ports:
    - "${PORT}:9000"