.catalog:
  name: Apache Solr
  description: |
    Apache Solr
  version: 6.6.0
  category: Big Data
  maintainer: mathias.kluba@gmail.com
  projectURL: http://lucene.apache.org/solr/
  - variable: "core_name"
      description: "Name of the core"
      label: "Core name:"
      required: true
      default: "mycore" 
      type: "string"
ambari-server-database:
  retain_ip: true
  scale: 1
  start_on_create: true
  health_check:
    response_timeout: 2000
    healthy_threshold: 2
    port: 8983
    unhealthy_threshold: 3
    initializing_timeout: 600000
    interval: 2000
    strategy: none
    reinitializing_timeout: 600000
