graylog-mongo:
    image: mongo:3
graylog-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    environment:
      - http.host=0.0.0.0
      # Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/security-settings.html#general-security-settings
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
graylog:
    image: graylog/graylog:2.3.2-1
    environment:
        GRAYLOG_PASSWORD_SECRET: somepasswordpepper
        GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
        GRAYLOG_WEB_ENDPOINT_URI: "http://127.0.0.1:${PORT}/api"
    links:
    - graylog-mongo:mongo
    - graylog-elasticsearch:graylog-elasticsearch
    ports:
    - "${PORT}:9000"